language: php

php:
  - 7.3

script:
  - ./tools/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

jobs:
  include:
    - stage: "Static Code Analysis"
      php: 7.3
      env: php-cs-fixer
      install:
        - phpenv config-rm xdebug.ini
      script:
        - ./tools/php-cs-fixer fix --dry-run -v --show-progress=dots --diff-format=udiff
    - stage: "Static Code Analysis"
      php: 7.3
      env: psalm
      install:
        - phpenv config-rm xdebug.ini
      script:
        - ./tools/psalm --no-progress --shepherd --stats
